version: '3'

x-common-settings: &common-settings
  restart: always
  platform: linux/amd64

volumes:
  redmine_mysql_data:
    driver: local
  gitbucket_postgres_data:
    driver: local
  redmine_data:
    driver: local
  gitbucket_data:
    driver: local
  jenkins_data:
    driver: local
services:
  # redmine_mysql
  redmine_mysql:
    <<: *common-settings
    image: mysql:latest
    volumes:
      - redmine_mysql_data:/var/lib/mysql
      - ./redmine_mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_USER: redmine
      MYSQL_PASSWORD: passwd
      MYSQL_DATABASE: redmine_production
  # gitbucket postgres
  gitbucket_postgres:
    image: postgres:latest
    volumes:
      - gitbucket_postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: passwd
      POSTGRES_USER: gitbucket
      POSTGRES_DB: gitbucket
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
  # redmine
  redmine:
    <<: *common-settings
    image: sameersbn/redmine:latest
    volumes:
      - gitbucket_data:/gitbucket
      - redmine_data:/home/redmine/data
    depends_on:
      - redmine_mysql
    environment:
      TZ: Asia/Tokyo
      REDMINE_RELATIVE_URL_ROOT: /redmine
      DB_HOST: redmine_mysql
      DB_USER: redmine
      DB_PASS: passwd
      SMTP_USER: address@example.com
      SMTP_PASS: password
  # gitbucket
  gitbucket:
    image: gitbucket/gitbucket:latest
    depends_on:
      - gitbucket_postgres
    environment:
      GITBUCKET_DB_URL: "jdbc:postgresql://gitbucket_postgres/gitbucket"
      GITBUCKET_DB_USER: gitbucket
      GITBUCKET_DB_PASSWORD: passwd
      GITBUCKET_PREFIX: /gitbucket
    volumes:
      - gitbucket_data:/gitbucket
    ports:
      - "29418:29418"
  # jenkins
  jenkins:
    image: jenkins/jenkins:lts-jdk21
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - jenkins_data:/var/jenkins_home
  # reverse-proxy
  proxy:
    build: proxy
    depends_on:
      - jenkins
      - redmine
      - gitbucket
    links:
      - gitbucket:gitbucket
      - redmine:redmine
      - jenkins:jenkins
    ports:
      - "80:80"
